### ISSUE TITLE
Fix "Login using facebook" feature

### ISSUE THREAD

**Issue by BukerKo** [BukerKo/coderunner-service#10]
User can't login using facebook.
The error is written in URL (ha-ha).

Steps to reproduce:
1. Click on "Login to facebook"
2. Login using valid credentials

Observe:
User gets redirected to login page with the following URL:
https://coderunner.tcomad.tk/login?error=could%20not%20execute%20statement;%20nested%20exception%20is%20org.hibernate.exception.GenericJDBCException:%20could%20not%20execute%20statement#_=_

Expected result:
User is redirected to Coderunner page

**Comment by Misha999777** [comment]
Fixed without code changes.

**Comment by BukerKo** [comment]
What was the problem?

**Comment by Misha999777** [comment]
AWS RDS settings not using UTF-8 and as a result Hibernate was not able to save our names to DB
