### ISSUE TITLE
S3

### ISSUE THREAD

**Issue by BukerKo** [BukerKo/coderunner-service#7]
Investigate possibility to use S3 for storing user's code.

**Comment by Misha999777** [comment]
S3 can be used for storing user's code files. AWS have a free trial tier for the S3 so it will be free to test it. AWS also provides Java library for their services including S3. Using S3 will make it harder to move from AWS to another cloud system in future so I recommend to implement both S3 and local storage at once. Example of implementation is avaliable here: https://github.com/tCoMaD/UniBot-Service/blob/master/src/main/java/tk/tcomad/unibot/service/S3FileStorageService.java

**Comment by BukerKo** [comment]
Ok, then let's have 2 different services (one for local storage and one for S3) for maintaining the ability to switch between them. For now let's use S3 storage and when we'll be moving let's switch to local.

**Comment by Misha999777** [comment]
https://github.com/BukerKo/coderunner-service/pull/11
